apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        applicationId "com.mdsd.docare.hemodialysis.app"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode 7
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

// applicationVariants.all { variant ->
//     variant.outputs.all { output ->
//         output.outputFileName = "${variant.buildType.name}-${variant.versionName}.apk"
//     }
// }

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.jph.takephoto:takephoto_library:4.0.3'
    implementation project(':hemomobile_library')
    implementation 'com.alibaba:fastjson:1.1.34'
    implementation 'org.greenrobot:eventbus:3.1.1'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-media-compat:28.0.0'
}